### ISSUE TITLE
Optimize on all available indicators in a package

### ISSUE THREAD

**Issue by sword134** [jmrichardson/tuneta#1]
Hello,
I've recently just found this library and must say it looks promising. I am wondering if there is a way to optimize on all indicators in one of the 3 packages (or perhaps mix and match all the indicators in the packages). Right now it looks as if you must input each indicator individually which is obviously not optimal.

**Comment by jmrichardson** [comment]
Good suggestions. I will look to implement that soon. Out of town at the moment. In the mean time, you have to manually create the list of indicators of interest.

**Comment by jmrichardson** [comment]
Hi @sword134 , I have added the ability to add indicators at the package level and all.  Examples:

- ['all']
- ['tta', 'fta']
- ['pta', 'tta.MACD', 'tta.ARRON:1]

Please install via clone method and let me know how it goes.  Thanks

**Comment by sword134** [comment]
@jmrichardson that was very fast. Thank you so much!
