### ISSUE TITLE
Strange errors occur when running on Colab

### ISSUE THREAD

**Issue by QAQOAO** [jmrichardson/tuneta#14]
Hi, very glad to see you make a huge update regarding my previous requests.

However, when I just copy paste all the code you provide in the example folder and execute on Colab, two strange errors emerges.

**The first one is in tune_market.py.**

-------------------------------------------------------------------------------------

from tuneta.tune_ta import TuneTA
import pandas as pd
from pandas_ta import percent_return
from sklearn.model_selection import train_test_split
import yfinance as yf
import joblib

aapl = yf.download("AAPL", period="10y", interval="1d", auto_adjust=True)
aapl['sym'] = "AAPL"
aapl.set_index('sym', append=True, inplace=True)
aapl['return'] = percent_return(aapl.Close, offset=-1)

msft = yf.download("MSFT", period="10y", interval="1d", auto_adjust=True)
msft['sym'] = "MSFT"
msft.set_index('sym', append=True, inplace=True)
msft['return'] = percent_return(msft.Close, offset=-1)

goog = yf.download("GOOG", period="10y", interval="1d", auto_adjust=True)
goog['sym'] = "GOOG"
goog.set_index('sym', append=True, inplace=True)
goog['return'] = percent_return(goog.Close, offset=-1)

X = pd.concat([aapl, msft, goog], axis=0).sort_index()
y = X['return']
X = X.drop(columns=['return'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, shuffle=False)

tt = TuneTA(n_jobs=4, verbose=True)

tt.fit(X_train, y_train,
    indicators=['tta.RSI', 'tta.MACD', 'tta.SMA', 'tta.CMO'],
    ranges=[(2, 30), (31, 60)],
    trials=300,
    early_stop=50,
)

-------------------------------------------------------------------------------------

Running the code above raise an error below, I am not sure what is the reason. Maybe some bugs exist when using Colab.

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-15-5ef2213dcedb> in <module>()
     38         ranges=[(2, 30), (31, 60)],
     39         trials=300,
---> 40         early_stop=50,
     41     )
     42 

2 frames
/usr/local/lib/python3.7/dist-packages/multiprocess/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

ValueError: ('Lengths must match to compare', (5285,), (2,))

**The second one is in tune_all.py.**

-------------------------------------------------------------------------------------

from tuneta.tune_ta import TuneTA
import pandas as pd
from pandas_ta import percent_return
from sklearn.model_selection import train_test_split
import yfinance as yf

X = yf.download("SPY", period="10y", interval="1d", auto_adjust=True)
y = percent_return(X.Close, offset=-1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, shuffle=False)

tt = TuneTA(n_jobs=6, verbose=True)

tt.fit(X_train, y_train,
    indicators=['all'],
    ranges=[(2, 30)],
    trials=500,
    early_stop=100,
)

-------------------------------------------------------------------------------------

Running the code above raise an error below, I am not sure what is the reason too. Maybe some bugs exist when using Colab.

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-16-c744cd5fb34d> in <module>()
     20     ranges=[(2, 30)],
     21     trials=500,
---> 22     early_stop=100,
     23 )
     24 

2 frames
/usr/local/lib/python3.7/dist-packages/multiprocess/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

AttributeError: 'KMeans' object has no attribute 'elbow_value_'

Thanks for you contribution again.

**Comment by jmrichardson** [comment]
Thanks for reporting the issue.  I have been avoiding specifying package versions required by tuneta, but it seems that I have to at least specify a minimum version to avoid these errors.  Essentially, a few packages where outdated which caused the problems.  I have updated the requirements file and should be working now.   I have also included a notebook for reference:

https://github.com/jmrichardson/tuneta/blob/main/notebooks/tune_market.ipynb

Will probably add more later but you should be able to test the code with the above.  Let me know if you run into any issues

**Comment by QAQOAO** [comment]
Thanks to your quick response.

I tried your code and it worked, but when I changed some parameters another error occurred.

The only changes I made are n_jobs=10, and indicators=['all'].

Maybe there are some indicators outputting invalid data type or there are some indicators do not support period > 30.

---------------------------------------------------------------------------------------------------------------

RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 113, in _objective
    res = [multi_obj_res(X, self.function, self.idx, trial) for _, X in X.groupby(level=1)]
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 113, in <listcomp>
    res = [multi_obj_res(X, self.function, self.idx, trial) for _, X in X.groupby(level=1)]
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 91, in multi_obj_res
    res = eval(function)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pandas_ta/statistics/tos_stdevall.py", line 38, in tos_stdevall
    m, b = npPolyfit(X, close, 1)
  File "<__array_function__ internals>", line 6, in polyfit
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/polynomial.py", line 621, in polyfit
    x = NX.asarray(x) + 0.0
TypeError: can only concatenate tuple (not "float") to tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 179, in fit
    n_trials=self.n_trials, callbacks=[_early_stopping_opt])
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/study.py", line 409, in optimize
    show_progress_bar=show_progress_bar,
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 76, in _optimize
    progress_bar=progress_bar,
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 264, in _run_trial
    raise func_err
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 178, in <lambda>
    self.study.optimize(lambda trial: _objective(self, trial, X, y),
  File "/usr/local/lib/python3.7/dist-packages/tuneta/optimize.py", line 118, in _objective
    raise RuntimeError(f"Optuna execution error: {self.function}")
RuntimeError: Optuna execution error: pta.tos_stdevall(X.close, length=trial.suggest_int('length', 2, 30), )
"""

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-5-98e279e3bc71> in <module>()
      7     ranges=[(2, 30), (31, 60)],
      8     trials=300,
----> 9     early_stop=50,
     10 )

2 frames
/usr/local/lib/python3.7/dist-packages/multiprocess/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

RuntimeError: Optuna execution error: pta.tos_stdevall(X.close, length=trial.suggest_int('length', 2, 30), )

**Comment by jmrichardson** [comment]
Hi, It looks like pandas-ta also needs to be upgraded.  You can try !pip install pandas-ta -U.    I have got a long day at kids soccer tournaments today so likely tonight or tomorrow before I can push the update.

**Comment by jmrichardson** [comment]
This has been a good exercise and hopefully the issues will be resolved soon :)  I really need to do unit testing but too busy to add now.  Yes, forgot to add the same logic to transform that I did yesterday.  I have run it on colab in it's entirety and no issues.  Please let me know how it goes.  Also, I was able to use joblib with any issues:

![image](https://user-images.githubusercontent.com/6565528/136813178-aee2b49b-d27e-4e2c-98ec-6541ac9a9c24.png)

If you still have issues with joblib, let me know
