### ISSUE TITLE
Warning: Future data leak

### ISSUE THREAD

**Issue by cryptocoinserver** [jmrichardson/tuneta#17]
pandas-ta has 2 indicators to be aware of:

Potential Data Leaks: dpo and ichimoku. See indicator list below for details. Set lookahead=False to disable.
https://twopirllc.github.io/pandas-ta/

**Comment by jmrichardson** [comment]
Thanks for reporting this.  I went ahead and commented them out of the default configuration as tuneta doesn't currently have the ability to set parameters for a specific indicator.  They can be added back manually but probably not a good idea.

**Comment by cryptocoinserver** [comment]
Perfect.
