### ISSUE TITLE
Enhancement: mamode, db_url, and get_indicator_params func

### ISSUE THREAD

**Issue by CMobley7** [jmrichardson/tuneta#22]
@jmrichardson ,

I plan to add a PR in about 2 weeks with the following enhancements from @wouldayajustlookatit branch. 

* tuneable mamode
* db_url; so that, users can see all runs tried in the optuna-dashboard
* function similar to wouldayajustlookatit's get_indicator_params, but I'm thinking something similar to the following; so that, it can easily be used with pandas-ta's strategies. 
`ta=[
        {"kind": "sma", "length": 50},
        {"kind": "sma", "length": 200},
        {"kind": "bbands", "length": 20},
        {"kind": "rsi"},
        {"kind": "macd", "fast": 8, "slow": 21},
        {"kind": "sma", "close": "volume", "length": 20, "prefix": "VOLUME"},
    ]`

Unfortunately, I didn't have enough time this weekend to finish adding those features and won't have time to add them until the following week. Are these are features you'd be interested in merging?

**Comment by jmrichardson** [comment]
@CMobley7 ,

These all look like great features to add and happy to merge your PR when available :)

As far as features to add, I don't have any in mind at the moment.  I have been working on another project designed to automate financial machine learning tasks (especially reuse of code) for investing in equities.  TuneTA is integrated for feature engineering.  I already have a significant amount of work done but looking for help if it interests you? 

Looking forward to your PR in a couple of weeks!

**Comment by CMobley7** [comment]
@jmrichardson ,

Awesome, thank you! I should have a PR in about 2 weeks. In regards to the other project, I might be able to help. What do you need help with specifically?

**Comment by jmrichardson** [comment]
Hi @CMobley7 ,

I am looking for a collaborator versus specific help in any one area.  I guess it depends on your interest in algorithmic trading inclusive of ML.  My goal with the framework is to easily be able to test ideas and create the process flow with minimal code.  Because the framework is modular, code can be easily shared within the community of developers.  I will work on the documentation a bit and if you are interested, I can invite you to the repo and see if it is something you would like to participate?   I am currently working on the backtest engine which I am moving from backtrader to vectorbt for performance reasons.

**Comment by CMobley7** [comment]
@jmrichardson ,

My apologies for the delayed reply, I've been on vacation. In regards to collaboration, I am interested. I'm in the process of creating the full data processing pipeline for an AI/ML algorithmic trading bot myself. The AI/ML is the easier part for me as I've been working in that field for years. The data processing has been utterly boring, but necessary as the quality of the AI/ML model is dependent on the input features.

**Comment by CMobley7** [comment]
I should hopefully have a PR in tonight for the tuneable mamode and db_url

**Comment by jmrichardson** [comment]
@CMobley7 ,

Hope you had a great vacation!  I am in need of one soon myself :)

Completely agree with you regarding the focus on data processing and AI/ML being the simple part.  Happy to hear that you are interested, and perhaps we should take this conversation offline?  My email is jmrichardson AT gmail if you want to discuss further.  I do have quite a bit of feature engineering modules that I have ported to the framework I am working on that all have a scikit interface.  I also have another repo for GP based features and others but haven't integrated it yet.  I am still working on the process workflow(s) to be as flexible as possible.  Interested in hearing about your algo trading bot as well.  

Also looking forward to your PR!
