### ISSUE TITLE
All indicators that don’t require volume?

### ISSUE THREAD

**Issue by Reed-Schimmel** [jmrichardson/tuneta#23]
Some assets, like FX, don’t have true volume data. I would like to be able to generate all features that do not require the volume column. This could be generalized to any of the OHLCV. How would I use tuneta to make all indicators that don’t require the volume column?

**Comment by jmrichardson** [comment]
Tuneta doesn't have a feature to filter indicators based on input.  Feel free to create a PR if you'd like but at the moment you could just maintain a manual list.  The list of indicators supported are found in [config.py](https://github.com/jmrichardson/tuneta/blob/main/tuneta/config.py).
