### ISSUE TITLE
Using Tuneta on long short portfolio of stocks

### ISSUE THREAD

**Issue by AnkitAggarwalAlphagrep** [jmrichardson/tuneta#30]
Hi

Thanks for creating this library. It is working out good on the dataset. However, I'm trying to use tuneta over the long short portfolio ( which contains multiple stocks). Is there a way to use the tuneta for the same indicator with same param over the group of stocks or any other way you can suggest?

Thanks,
Ankit Aggarwal

**Comment by jmrichardson** [comment]
Hi @AnkitAggarwalAlphagrep 

Yes, take a look at the readme in the section "Tune Market".  Essentially, you just need to index your dataframes with date/indicator and it works the same across the basket of stocks.  Let me know if you have any questions.
